<?php

namespace App\Services\Postgis;

use App\Enums\DatasetFieldType;
use App\Enums\DatasetFormVersionStatus;
use App\Enums\GeoLayerAccessPolicy;
use App\Models\DatasetFormField;
use App\Models\DatasetFormVersion;
use App\Models\GeoLayer;
use App\Models\SpatialDataset;
use App\Models\SpatialImport;
use App\Models\SpatialImportContract;
use Illuminate\Support\Facades\DB;
use RuntimeException;
use Throwable;

class MaterializeSpatialDataset
{
    public function isAvailable(): bool
    {
        return DB::getDriverName() === 'pgsql';
    }

    public function materialize(SpatialDataset $dataset): void
    {
        $originalConnection = DB::getDefaultConnection();
        if ($originalConnection === 'managed_postgis' && config('database.connections.managed_postgis_admin')) {
            DB::setDefaultConnection('managed_postgis_admin');
            DB::purge('managed_postgis_admin');
        }

        try {
            $this->materializeOnCurrentConnection($dataset);
        } finally {
            DB::setDefaultConnection($originalConnection);
            if ($originalConnection === 'managed_postgis') {
                DB::purge('managed_postgis_admin');
            }
        }
    }

    private function materializeOnCurrentConnection(SpatialDataset $dataset): void
    {
        if (DB::getDriverName() !== 'pgsql') {
            throw new RuntimeException('La materialización espacial requiere PostgreSQL con PostGIS. SQLite permanece sin cambios.');
        }

        $version = $dataset->versions()
            ->where('status', DatasetFormVersionStatus::Published->value)
            ->with('fields')
            ->latest('version')
            ->first();

        if ($version === null) {
            throw new RuntimeException("El conjunto {$dataset->slug} no tiene un formulario publicado.");
        }

        $table = $this->tableName($dataset->slug);
        $storageSrid = $dataset->storage_srid;

        try {
            DB::transaction(function () use ($dataset, $version, $table, $storageSrid): void {
                DB::statement('CREATE EXTENSION IF NOT EXISTS postgis');
                DB::statement('CREATE EXTENSION IF NOT EXISTS pgcrypto');
                if ($dataset->geometry_type !== 'none'
                    && ! DB::selectOne('SELECT 1 AS present FROM spatial_ref_sys WHERE srid = ?', [$storageSrid])) {
                    throw new RuntimeException("EPSG:{$storageSrid} no está registrado en PostGIS. Revise el sistema de coordenadas antes de crear la tabla operativa.");
                }
                DB::statement('CREATE SCHEMA IF NOT EXISTS capture');
                DB::statement('CREATE SCHEMA IF NOT EXISTS publication');
                $qgisRole = (string) config('database.managed_roles.qgis', 'qgis_editor');
                $readerRole = (string) config('database.managed_roles.reader', 'geoserver_reader');
                $qgisRoleLiteral = $this->stringLiteral($qgisRole);
                DB::unprepared(<<<SQL
                    CREATE OR REPLACE FUNCTION capture.guard_qgis_workflow()
                    RETURNS trigger
                    LANGUAGE plpgsql
                    AS $$
                    BEGIN
                        IF NEW.source = 'qgis'
                           AND pg_has_role(session_user, {$qgisRoleLiteral}, 'member')
                           AND NEW.record_status NOT IN ('draft', 'submitted') THEN
                            RAISE EXCEPTION 'QGIS sólo puede guardar borradores o enviar registros a revisión.';
                        END IF;

                        IF TG_OP = 'INSERT' THEN
                            NEW.created_by_email = COALESCE(NEW.created_by_email, session_user);
                        END IF;
                        NEW.updated_at = CURRENT_TIMESTAMP;

                        RETURN NEW;
                    END;
                    $$
                    SQL);

                $qualifiedCapture = $this->qualified('capture', $table);
                $columns = [
                    '"fid" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
                    '"id" uuid NOT NULL DEFAULT gen_random_uuid()',
                    '"form_version" integer NOT NULL DEFAULT '.(int) $version->version,
                    '"record_status" text NOT NULL DEFAULT \'draft\' CHECK ("record_status" IN (\'draft\', \'submitted\', \'validated\', \'published\'))',
                    '"source" text NOT NULL DEFAULT \'qgis\'',
                    '"created_by_email" text NULL',
                    '"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP',
                    '"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP',
                ];

                if ($dataset->geometry_type !== 'none') {
                    $columns[] = '"geom" geometry('.$this->postgisGeometryType($dataset->geometry_type).', '.(int) $storageSrid.') NULL';
                }

                DB::statement("CREATE TABLE IF NOT EXISTS {$qualifiedCapture} (".implode(', ', $columns).')');
                $qualifiedView = $this->qualified('publication', $table);
                DB::statement("DROP VIEW IF EXISTS {$qualifiedView}");
                $this->ensureGeometryColumnType($dataset, $qualifiedCapture, $table);

                $primaryKey = $this->quoteIdentifier($this->shortIdentifier($table.'_pkey'));
                $uuidIndex = $this->quoteIdentifier($this->shortIdentifier($table.'_id_unique'));
                DB::statement("ALTER TABLE {$qualifiedCapture} ADD COLUMN IF NOT EXISTS \"fid\" integer GENERATED BY DEFAULT AS IDENTITY");
                DB::statement("ALTER TABLE {$qualifiedCapture} DROP CONSTRAINT IF EXISTS {$primaryKey}");
                DB::statement("ALTER TABLE {$qualifiedCapture} ADD CONSTRAINT {$primaryKey} PRIMARY KEY (\"fid\")");
                DB::statement("ALTER TABLE {$qualifiedCapture} ALTER COLUMN \"id\" SET NOT NULL");
                DB::statement("CREATE UNIQUE INDEX IF NOT EXISTS {$uuidIndex} ON {$qualifiedCapture} (\"id\")");
                DB::statement("ALTER TABLE {$qualifiedCapture} ALTER COLUMN \"form_version\" SET DEFAULT ".(int) $version->version);

                foreach ($version->fields as $field) {
                    DB::statement("ALTER TABLE {$qualifiedCapture} ADD COLUMN IF NOT EXISTS {$this->quoteIdentifier($field->key)} {$this->columnType($field)} NULL");
                    $this->applyFieldMetadataAndRules($qualifiedCapture, $table, $field);
                }

                if ($dataset->geometry_type !== 'none') {
                    $index = $this->quoteIdentifier($this->shortIdentifier($table.'_geom_gix'));
                    DB::statement("CREATE INDEX IF NOT EXISTS {$index} ON {$qualifiedCapture} USING GIST (\"geom\")");
                }

                $statusIndex = $this->quoteIdentifier($this->shortIdentifier($table.'_status_idx'));
                DB::statement("CREATE INDEX IF NOT EXISTS {$statusIndex} ON {$qualifiedCapture} (\"record_status\")");
                DB::statement("DROP TRIGGER IF EXISTS \"guard_qgis_workflow\" ON {$qualifiedCapture}");
                DB::statement("CREATE TRIGGER \"guard_qgis_workflow\" BEFORE INSERT OR UPDATE ON {$qualifiedCapture} FOR EACH ROW EXECUTE FUNCTION capture.guard_qgis_workflow() ");

                $publicFields = $version->fields
                    ->where('public_visible', true)
                    ->map(fn (DatasetFormField $field): string => $this->quoteIdentifier($field->key))
                    ->all();
                $viewColumns = ['"id"'];
                if ($dataset->geometry_type !== 'none') {
                    $viewColumns[] = '"geom"';
                }
                array_push($viewColumns, '"form_version"', '"updated_at"', ...$publicFields);

                DB::statement("CREATE VIEW {$qualifiedView} AS SELECT ".implode(', ', $viewColumns)." FROM {$qualifiedCapture} WHERE \"record_status\" = 'published'");

                $quotedQgisRole = $this->quoteIdentifier($qgisRole);
                $quotedReaderRole = $this->quoteIdentifier($readerRole);
                $this->grantRoleIfPresent($qgisRole, [
                    "GRANT USAGE ON SCHEMA capture TO {$quotedQgisRole}",
                    "GRANT SELECT, INSERT, UPDATE, DELETE ON {$qualifiedCapture} TO {$quotedQgisRole}",
                    "GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA capture TO {$quotedQgisRole}",
                ]);
                $this->grantRoleIfPresent($readerRole, [
                    "GRANT USAGE ON SCHEMA publication TO {$quotedReaderRole}",
                    "GRANT SELECT ON {$qualifiedView} TO {$quotedReaderRole}",
                ]);
                $appRole = (string) config('database.connections.managed_postgis.username', 'siid_app');
                $quotedAppRole = $this->quoteIdentifier($appRole);
                $this->grantRoleIfPresent($appRole, [
                    "GRANT USAGE ON SCHEMA publication TO {$quotedAppRole}",
                    "GRANT SELECT ON {$qualifiedView} TO {$quotedAppRole}",
                ]);

                $this->promoteInitialImport($dataset, $version, $qualifiedCapture);

                $dataset->update([
                    'physical_table' => $table,
                    'materialized_form_version' => $version->version,
                    'materialized_at' => now(),
                    'materialization_error' => null,
                ]);

                GeoLayer::query()->firstOrCreate(['slug' => $dataset->slug], [
                    'name' => $dataset->name,
                    'group_name' => $dataset->sector,
                    'source_type' => 'geojson',
                    'source_url' => '/api/public/geodata/'.$dataset->slug,
                    'geometry_type' => $dataset->geometry_type,
                    'popup_fields' => $version->fields->where('public_visible', true)->pluck('key')->values()->all(),
                    'style' => ['color' => '#4338ca', 'fillColor' => '#818cf8', 'weight' => 2, 'radius' => 7],
                    'attribution' => 'Fuente: Gobernación del Meta',
                    'min_zoom' => 0,
                    'max_zoom' => 18,
                    'active' => true,
                    'access_policy' => GeoLayerAccessPolicy::Pending,
                ]);
            });
        } catch (Throwable $exception) {
            $dataset->update(['materialization_error' => $exception->getMessage()]);

            throw $exception;
        }
    }

    public function tableName(string $slug): string
    {
        return $this->shortIdentifier(str_replace('-', '_', $slug));
    }

    public function columnType(DatasetFormField $field): string
    {
        return match ($field->field_type) {
            DatasetFieldType::ShortText, DatasetFieldType::Select => $this->varcharType($field),
            DatasetFieldType::LongText => 'text',
            DatasetFieldType::Integer => 'bigint',
            DatasetFieldType::Decimal => 'numeric',
            DatasetFieldType::Date => 'date',
            DatasetFieldType::DateTime => 'timestamptz',
            DatasetFieldType::Boolean => 'boolean',
            DatasetFieldType::MultiSelect => 'jsonb',
        };
    }

    private function varcharType(DatasetFormField $field): string
    {
        $maxLength = (int) data_get($field->validation_rules, 'max_length', 500);

        return 'varchar('.max(1, min($maxLength, 10000)).')';
    }

    private function promoteInitialImport(SpatialDataset $dataset, DatasetFormVersion $version, string $qualifiedCapture): void
    {
        if ((int) DB::scalar("SELECT COUNT(*) FROM {$qualifiedCapture}") > 0) {
            return;
        }

        $contract = SpatialImportContract::query()
            ->with('import')
            ->where('spatial_dataset_id', $dataset->id)
            ->first();
        $import = $contract?->import ?? SpatialImport::query()
            ->where('spatial_dataset_id', $dataset->id)
            ->whereNotNull('selected_table')
            ->latest('created_at')
            ->first();
        if ($import === null) {
            return;
        }

        $mapping = $contract?->field_mapping ?? $import->field_mapping ?? [];
        $validFields = $version->fields->pluck('key')->flip();
        $columns = ['"record_status"', '"source"', '"created_by_email"'];
        $expressions = ["'published'", "'initial_import'", $this->stringLiteral($import->database_username)];

        foreach ($mapping as $source => $target) {
            if ($source === '_geometry' || ! is_string($target) || ! $validFields->has($target)) {
                continue;
            }
            $columns[] = $this->quoteIdentifier($target);
            $expressions[] = $this->quoteDatabaseIdentifier((string) $source);
        }

        $geometry = $mapping['_geometry'] ?? null;
        if ($dataset->geometry_type !== 'none' && is_array($geometry) && isset($geometry['source'])) {
            $sourceGeometry = $this->quoteDatabaseIdentifier((string) $geometry['source']);
            $srid = (int) ($geometry['srid'] ?? 0);
            if ($srid <= 0) {
                throw new RuntimeException('La capa importada no tiene un sistema de coordenadas identificable. Corrija su CRS en QGIS antes de publicar.');
            }
            $columns[] = '"geom"';
            $transformedGeometry = "ST_Transform({$sourceGeometry}, ".(int) $dataset->storage_srid.')';
            if (in_array($dataset->geometry_type, ['line', 'polygon'], true)) {
                $transformedGeometry = "ST_Multi({$transformedGeometry})";
            }
            $expressions[] = "CASE WHEN {$sourceGeometry} IS NULL THEN NULL ELSE {$transformedGeometry} END";
        }

        $sourceTable = $this->quoteIdentifier($import->staging_schema).'.'.$this->quoteDatabaseIdentifier((string) ($contract?->source_table ?? $import->selected_table));
        DB::statement("INSERT INTO {$qualifiedCapture} (".implode(', ', $columns).') SELECT '.implode(', ', $expressions)." FROM {$sourceTable}");
    }

    private function applyFieldMetadataAndRules(string $qualifiedTable, string $table, DatasetFormField $field): void
    {
        $column = $this->quoteIdentifier($field->key);
        $comment = json_encode([
            'label' => $field->label,
            'help_text' => $field->help_text,
            'unit' => $field->unit,
            'introduced_in_version' => $field->introduced_in_version,
            'historical_policy' => $field->historical_policy->value,
        ], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR);
        DB::statement("COMMENT ON COLUMN {$qualifiedTable}.{$column} IS ".$this->stringLiteral($comment));

        $rules = [];
        if ($field->required) {
            $rules['required'] = '"form_version" < '.(int) $field->introduced_in_version." OR {$column} IS NOT NULL";
        }
        if (is_numeric(data_get($field->validation_rules, 'min'))) {
            $rules['min'] = "{$column} IS NULL OR {$column} >= ".(float) data_get($field->validation_rules, 'min');
        }
        if (is_numeric(data_get($field->validation_rules, 'max'))) {
            $rules['max'] = "{$column} IS NULL OR {$column} <= ".(float) data_get($field->validation_rules, 'max');
        }
        if ($field->field_type === DatasetFieldType::Select && $field->options !== null) {
            $allowed = collect($field->options)->map(fn (string $option): string => $this->stringLiteral($option))->implode(', ');
            if ($allowed !== '') {
                $rules['options'] = "{$column} IS NULL OR {$column} IN ({$allowed})";
            }
        }

        foreach ($rules as $suffix => $expression) {
            $constraint = $this->quoteIdentifier($this->shortIdentifier($table.'_'.$field->key.'_'.$suffix.'_chk'));
            DB::statement("ALTER TABLE {$qualifiedTable} DROP CONSTRAINT IF EXISTS {$constraint}");
            DB::statement("ALTER TABLE {$qualifiedTable} ADD CONSTRAINT {$constraint} CHECK ({$expression}) NOT VALID");
        }
    }

    private function stringLiteral(string $value): string
    {
        $quoted = DB::connection()->getPdo()->quote($value);
        if (! is_string($quoted)) {
            throw new RuntimeException('No fue posible codificar un valor para PostgreSQL.');
        }

        return $quoted;
    }

    public function postgisGeometryType(string $type): string
    {
        return match ($type) {
            'point' => 'Point',
            'line' => 'MultiLineString',
            'polygon' => 'MultiPolygon',
            default => throw new RuntimeException("Tipo de geometría no compatible: {$type}."),
        };
    }

    private function ensureGeometryColumnType(SpatialDataset $dataset, string $qualifiedCapture, string $table): void
    {
        if ($dataset->geometry_type === 'none') {
            return;
        }

        $column = DB::selectOne(
            'SELECT type, srid FROM geometry_columns WHERE f_table_schema = ? AND f_table_name = ? AND f_geometry_column = ?',
            ['capture', $table, 'geom'],
        );
        if ($column === null) {
            throw new RuntimeException("La tabla capture.{$table} no tiene una columna geom reconocida por PostGIS.");
        }

        $expectedType = $this->postgisGeometryType($dataset->geometry_type);
        if ((int) $column->srid !== $dataset->storage_srid) {
            throw new RuntimeException("La tabla capture.{$table} usa EPSG:{$column->srid}, distinto al EPSG:{$dataset->storage_srid} configurado.");
        }
        if (mb_strtoupper((string) $column->type) === mb_strtoupper($expectedType)) {
            return;
        }

        $previousType = match ($dataset->geometry_type) {
            'line' => 'LINESTRING',
            'polygon' => 'POLYGON',
            default => null,
        };
        if (mb_strtoupper((string) $column->type) !== $previousType) {
            throw new RuntimeException("La tabla capture.{$table} tiene geometría {$column->type}; se esperaba {$expectedType}.");
        }

        DB::statement("ALTER TABLE {$qualifiedCapture} ALTER COLUMN \"geom\" TYPE geometry({$expectedType}, ".(int) $dataset->storage_srid.') USING ST_Multi("geom")');
    }

    private function qualified(string $schema, string $table): string
    {
        return $this->quoteIdentifier($schema).'.'.$this->quoteIdentifier($table);
    }

    private function quoteIdentifier(string $identifier): string
    {
        if (! preg_match('/^[a-z][a-z0-9_]*$/', $identifier)) {
            throw new RuntimeException("Identificador PostgreSQL no válido: {$identifier}.");
        }

        return '"'.$identifier.'"';
    }

    private function quoteDatabaseIdentifier(string $identifier): string
    {
        return '"'.str_replace('"', '""', $identifier).'"';
    }

    private function shortIdentifier(string $identifier): string
    {
        if (mb_strlen($identifier) <= 63) {
            return $identifier;
        }

        return mb_substr($identifier, 0, 52).'_'.mb_substr(hash('sha256', $identifier), 0, 10);
    }

    /** @param array<int, string> $statements */
    private function grantRoleIfPresent(string $role, array $statements): void
    {
        $exists = DB::selectOne('SELECT 1 AS present FROM pg_roles WHERE rolname = ?', [$role]);
        if ($exists === null) {
            return;
        }

        foreach ($statements as $statement) {
            DB::statement($statement);
        }
    }
}
